name: Bug Report
description: Create a report to help us improve
title: "[Bug]: "
labels: [type:bug]
body:
  - type: checkboxes
    id: searched-for-existing-issues
    attributes:
      label: Existing Issues
      description: Before submitting this, please make sure to search for [existing issues](https://github.com/cryptomator/cryptomator/issues?q=)
      options:
      - label: I have searched the existing issues
        required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/cryptomator/cryptomator/blob/develop/.github/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
  - type: input
    id: summary
    attributes:
      label: Summary
      description: Please summarize your problem.
    validations:
      required: true
  - type: textarea
    id: software-versions
    attributes:
      label: What software is involved?
      description: |
        examples:
          - **OS**: Windows 10
          - **Cryptomator**: 1.5.16
          - **LibreOffice**: 7.1.4
      value: |
          - **OS**: 
          - **Cryptomator**: 
          - ...
      render: markdown
    validations:
      required: true
  - type: dropdown
    id: volume-type
    attributes:
      label: Volume Type
      description: What is selected under Settings → Virtual Drive?
      multiple: true
      options:
        - FUSE
        - Dokany
        - WebDAV
    validations:
      required: false
  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to Reproduce
      description: |
        examples:
          1. Click *Unlock...*
          2. Enter no password
          3. Hit enter
      value: |
        1. [First step]
        2. [Second step]
        3. [and so on…]
      render: markdown
    validations:
      required: true
  - type: textarea
    id: expected-behaviour
    attributes:
      label: Expected Behavior
      description: What you expect to happen.
      render: markdown
    validations:
      required: true
  - type: textarea
    id: actual-behaviour
    attributes:
      label: Actual Behavior
      description: What actually happens.
      render: markdown
    validations:
      required: true
  - type: dropdown
    id: reproducibility
    attributes:
      label: Reproducibility
      description: How often does the described behaviour occur?
      options:
        - Always
        - Intermittent
        - Only once
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: textarea
    id: further-info
    attributes:
      label: Anything else?
      description: Links? References? Screenshots? Configurations? Any data that might be necessary to reproduce the issue?