name: Feature Request
description: Suggest an idea for this project
title: "[Feature]: "
labels: ["type:feature-request"]
body:
  - type: checkboxes
    id: searched-for-existing-issues
    attributes:
      label: Existing Issues
      description: Before submitting this, please make sure to search for [existing issues](https://github.com/cryptomator/cryptomator/issues?q=)
      options:
      - label: I have searched the existing issues
        required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/cryptomator/cryptomator/blob/develop/.github/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
  - type: input
    id: summary
    attributes:
      label: Summary
      description: Please summarize your feature request
    validations:
      required: true
  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: |
        Who requires this feature?
        What problem does the user face?
        How would this feature solve the problem?
      render: markdown
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Considered Alternatives
      description: What current alternatives or workarounds have you considered? Is there a different way to solve the same problem?
      render: markdown
  - type: textarea
    id: context
    attributes:
      label: Anything else?
      description: Any context, suggestions, screenshots or concepts you want to share?
      render: markdown