name: Java CI

on: 
 [push]

env:
  APP_NAME: helloJavaFX
  KIT_NAME: kit
  PKG_NAME: pkg
  BUILD_VERSION: SNAPSHOT

jobs:
  build:
    name: Creates the executable Javafx test apps for different systems
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    outputs:
      artifact-version: SNAPSHOT #${{ steps.setversion.outputs.version }}
    env:
      TARGET_OS: ANY
    steps:
    - name: Set correct OS label (win)
      if: ${{ runner.os == 'Windows' }}
      run: echo "::set-env name=TARGET_OS::win"
    - name: Set correct OS label (mac)
      if: ${{ runner.os == 'macOS' }}
      run: echo "::set-env name=TARGET_OS::mac"
    - name: Set correct OS label (linux)
      if: ${{ runner.os == 'Linux' }}
      run: echo "::set-env name=TARGET_OS::linux"
    - uses: actions/checkout@v1
    - name: Set up JDK 14
      uses: actions/setup-java@v1
      with: 
        java-version: 14
    - uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Ensure to use tagged version
      run: |
        mvn versions:set --file pom.xml -DnewVersion=${GITHUB_REF##*/} # use shell parameter expansion to strip of 'refs/tags'
        echo "::set-env name=BUILD_VERSION::${GITHUB_REF##*/}"
      if: startsWith(github.ref, 'refs/tags/')
    - name: Build buildkit with Maven
      run: mvn -B install --file pom.xml -Pbuildkit
    - name: Uploads the buildkit for possible further use
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.APP_NAME }}-${{ env.KIT_NAME }}-${{ env.BUILD_VERSION }}-${{ env.TARGET_OS }}
        path: target/javafx-testkit-${{ env.TARGET_OS }}.zip
    - name: Build package with Maven
      run: mvn -B package --file pom.xml -Ppackage -DruntimeImageAlreadyBuild=true
    - name: Uploads the package for possible further use
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.APP_NAME }}-${{ env.PKG_NAME }}-${{ env.BUILD_VERSION }}-${{ env.TARGET_OS }}
        path: target/javafx-helloworld*

  release:
    name: Draft a Release on GitHub Releases
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v2
      - name: Display structure of dowloaded files. This stepp will be removed with the next release.
        run: ls -R #TODO: remove this step and fix the ones below
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: |
            :construction: Work in Progress
          draft: true
          prerelease: false
      - name: Upload linux kit to GitHub Releases
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ env.APP_NAME }}-${{ env.KIT_NAME }}-${{ env.BUILD_VERSION }}-linux/${{ env.APP_NAME }}-${{ env.KIT_NAME }}-${{ env.BUILD_VERSION }}-linux.zip
          asset_name: ${{ env.APP_NAME }}-${{ env.KIT_NAME }}-${{ env.BUILD_VERSION }}-linux.zip
          asset_content_type: application/zip
      - name: Upload linux pkg to GitHub Releases
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ env.APP_NAME }}-${{ env.PKG_NAME }}-${{ env.BUILD_VERSION }}-linux/
          asset_name: ${{ env.APP_NAME }}-${{ env.PKG_NAME }}-${{ env.BUILD_VERSION }}-linux.zip
          asset_content_type: application/zip
      - name: Upload mac kit to GitHub Releases
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ env.APP_NAME }}-${{ env.KIT_NAME }}-${{ env.BUILD_VERSION }}-mac/${{ env.APP_NAME }}-${{ env.KIT_NAME }}-${{ env.BUILD_VERSION }}-mac.zip
          asset_name: ${{ env.APP_NAME }}-${{ env.KIT_NAME }}-${{ env.BUILD_VERSION }}-mac.zip
          asset_content_type: application/zip
      - name: Upload mac pkg to GitHub Releases
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ env.APP_NAME }}-${{ env.PKG_NAME }}-${{ env.BUILD_VERSION }}-mac/
          asset_name: ${{ env.APP_NAME }}-${{ env.PKG_NAME }}-${{ env.BUILD_VERSION }}-mac.zip
          asset_content_type: application/zip
      - name: Upload windows kit to GitHub Releases
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ env.APP_NAME }}-${{ env.KIT_NAME }}-${{ env.BUILD_VERSION }}-win/${{ env.APP_NAME }}-${{ env.KIT_NAME }}-${{ env.BUILD_VERSION }}-win.zip
          asset_name: ${{ env.APP_NAME }}-${{ env.KIT_NAME }}-${{ env.BUILD_VERSION }}-win.zip
          asset_content_type: application/zip
      - name: Upload windows pkg to GitHub Releases
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ env.APP_NAME }}-${{ env.PKG_NAME }}-${{ env.BUILD_VERSION }}-mac/
          asset_name: ${{ env.APP_NAME }}-${{ env.PKG_NAME }}-${{ env.BUILD_VERSION }}-mac.zip
          asset_content_type: application/zip
