name: Java CI

on: 
 [push]

env:
  APP_NAME: helloJavaFX

jobs:
  build:
    name: Creates the executable Javafx test apps for different systems
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    outputs:
      artifact-version: SNAPSHOT #${{ steps.setversion.outputs.version }}
    env:
      BUILD_VERSION: SNAPSHOT
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK
      uses: actions/setup-java@v1
      with: 
        java-version: 15
    - uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: If tag is set, use it as version
      run: echo "BUILD_VERSION=${GITHUB_REF##*/}" >> $GITHUB_ENV
      shell: bash
      if: startsWith(github.ref, 'refs/tags/')
    - name: Ensure to use tagged version in maven
      run: mvn versions:set --file pom.xml -DnewVersion=${{ env.BUILD_VERSION }}
      if: startsWith(github.ref,'refs/tags/')
    - name: Build runnable app with Maven
      run: mvn -B install --file pom.xml
    - name: Uploads the zip for possible further use
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.APP_NAME }}-SNAPSHOT-${{ runner.os }}
        path: target/helloJavaFX-*.[zt]*

  release:
    name: Draft a Release on GitHub Releases
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    env:
      BUILD_VERSION: DUMMY
    steps:
      - name: Get version from tag and set up environment
        run: echo "::set-env name=BUILD_VERSION::${GITHUB_REF##*/}"
      - name: Download all artifacts
        uses: actions/download-artifact@v2
      - name: Display structure of dowloaded files. This stepp will be removed with the next release.
        run: ls -R #TODO: remove this step and fix the ones below
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: |
            :construction: Work in Progress
          draft: true
          prerelease: false
      - name: Upload linux package to GitHub Releases
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ env.APP_NAME }}-SNAPSHOT-Linux/helloJavaFX-${{ env.BUILD_VERSION }}-linux.tar.gz
          asset_name: ${{ env.APP_NAME }}-${{ env.BUILD_VERSION }}-linux.tar.gz
          asset_content_type: application/gzip
      - name: Upload mac kit to GitHub Releases
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ env.APP_NAME }}-SNAPSHOT-macOS/helloJavaFX-${{ env.BUILD_VERSION }}-mac.zip
          asset_name: ${{ env.APP_NAME }}-${{ env.BUILD_VERSION }}-mac.zip
          asset_content_type: application/zip
      - name: Upload windows kit to GitHub Releases
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ env.APP_NAME }}-SNAPSHOT-Windows/helloJavaFX-${{ env.BUILD_VERSION }}-win.zip
          asset_name: ${{ env.APP_NAME }}-${{ env.BUILD_VERSION }}-win.zip
          asset_content_type: application/zip
