name: Create Release

on: 
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Creates the executable Javafx test apps for different systems
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]      
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 14
      uses: actions/setup-java@v1
      with: 
        java-version: 14
    - name: Build with Maven
      run: mvn -B install --file pom.xml
    - name: Uploads the build artifacts to use it in a possible release
      uses: actions/upload-artifact@v1
      with:
        name: javafx-testkit-${{matrix.os}}.zip
        path: target/javafx-testkit-${{matrix.os}}.zip
  release:
    name: Creates the release with the given tag and uploads all assets
    runs-on: ubuntu-latest
    needs: [build]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v1
      - id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Automated release via github actions
          draft: false
          prerelease: false
      - name: Downloads generated files (Linux)
        uses: actions/download-artifact@v1
        with:
          name: javafx-testkit-ubuntu-latest.zip
      - uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./javafx-testkit-ubuntu-latest.zip/javafx-testkit-ubuntu-latest.zip
          asset_name: javafx-testkit-linux.zip
          asset_content_type: application/zip
      - name: Downloads generated files (Windows)
        uses: actions/download-artifact@v1
        with:
          name: javafx-testkit-windows-latest.zip
      - uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./javafx-testkit-windows-latest.zip/javafx-testkit-windows-latest.zip
          asset_name: javafx-testkit-windows.zip
          asset_content_type: application/zip    
      - name: Downloads generated files (MacOS)
        uses: actions/download-artifact@v1
        with:
          name: javafx-testkit-macOS-latest.zip
      - uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./javafx-testkit-macOS-latest.zip/javafx-testkit-macOS-latest.zip
          asset_name: javafx-testkit-macOS.zip
          asset_content_type: application/zip
