name: Create Release

on: 
  push:
    tags:
      -'*'

jobs:
  build:
    name: Creates the executable Javafx test apps for different systems
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]      
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with: 
        java-version: 11
    - name: Build with Maven
      run: mvn -B install --file pom.xml
    - name: Uploads the build artifacts to use it in a possible release
      uses: actions/upload-artifact@v1
      with:
        name: javafx-testkit-${{matrix.os}}
        path: target/javafx-testkit-${{matrix.os}}.zip
  release:
    name: Create Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v1
      - id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Automated release via github actions
          draft: false
          prerelease: false
          
  publish:
    name: Uploads the assets
    runs-on: ubuntu-latest
    needs: [build, release]
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macOS-latest]
    steps:
      - name: Downloads generated files (Windows)
        uses: actions/download-artifact@v1
        with:
          name: javafx-testkit-${{matrix.os}}
      - uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_release_info.outputs.upload_url }}
          asset_path: ./javafx-testkit-${{matrix.os}}.zip
          asset_name: javafx-testkit-${{matrix.os}}.zip
          asset_content_type: application/zip
